name: bedwarsRL
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - black=24.*
  - isort=5.*
  - pre-commit=3.*
  - docformatter=1.7.*
  - flake8=7.*
  - jupyter=1.*
  - ipykernel
  - numpy=1.26.*
  - pip:
      - javascript==1!1.*
      - gymnasium
      - -e .
      - pytorchrl
